package com.bfunkstudios.beatclikr

import com.bfunkstudios.beatclikr.services.MetronomeAudioEngineDelegate
import com.bfunkstudios.beatclikr.services.PolyrhythmAudioEngineDelegate

abstract class MetronomeTestDelegate : MetronomeAudioEngineDelegate

abstract class PolyrhythmTestDelegate : PolyrhythmAudioEngineDelegate
